<?php

/**
 * Implements hook_theme().
 */
function mentor_theme() {
  $theme = [];
  $theme['recipe'] = [
    'render element' => 'elements',
    'file' => 'recipe.page.inc',
    'template' => 'recipe',
  ];
  $theme['recipe_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'recipe.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function mentor_theme_suggestions_recipe(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#recipe'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'recipe__' . $sanitized_view_mode;
  $suggestions[] = 'recipe__' . $entity->bundle();
  $suggestions[] = 'recipe__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'recipe__' . $entity->id();
  $suggestions[] = 'recipe__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * @param $links
 * Implements hook_menu_links_discovered_alter(&$links).
 */
function mentor_menu_links_discovered_alter(&$links) {
  if($links['system.admin_content']) {$links['system.admin_content']['title'] = t('Other content');}
}
